version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - saudi-market-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - saudi-market-network

networks:
  saudi-market-network:
    driver: bridge
